Feat/sidebar component
KATITB2023/dashboard-internal pull request #14
Opened 2023-07-26 16:11 UTC by ashnchiquita

## Story/Task
[Link Trello](https://trello.com/c/pvGWVon6/64-fe-navbar)
(sebenernya ini di trellonya namanya navbar tp aku keburu namainnya sidebar)

## Summary
- buat sidebar (udah dipisah admin/mentornya)
- nyesuain layout dan routing dgn link sidebar

## Screenshot
sidebar admin
![Screen Shot 2023-07-26 at 22 52 24](https://github.com/KATITB2023/dashboard-internal/assets/88751131/644580f8-d4ec-4702-8533-46459355b181)
![Screen Shot 2023-07-26 at 22 52 35](https://github.com/KATITB2023/dashboard-internal/assets/88751131/1e127710-d729-4fa8-86eb-186066ecfd6d)

sidebar mentor
![Screen Shot 2023-07-26 at 22 52 58](https://github.com/KATITB2023/dashboard-internal/assets/88751131/0b502089-7a51-41f9-a667-3861a9f07b6f)
![Screen Shot 2023-07-26 at 22 53 07](https://github.com/KATITB2023/dashboard-internal/assets/88751131/4186ce9c-6294-4a20-b1b2-806374857458)

2023-07-27 08:23 UTC, msyahrulsp requested changes
Overall dah ok, tapi boleh diubah dlu ya

2023-07-27 08:23 UTC, msyahrulsp commented on src/component/sidebar/component/Content.tsx
> +      </Flex>
Ini hapus aja, karena profile itu sama kayak group management

2023-07-27 08:23 UTC, msyahrulsp commented on src/component/sidebar/component/Content.tsx
> +      </Flex>
Sama, yang dummy content hapus aja (bisa bisa dimerge), terus navbarnya pasang di layout

2023-07-27 08:24 UTC, msyahrulsp commented on src/component/sidebar/component/Content.tsx
> +      </Flex>
![image](https://github.com/KATITB2023/dashboard-internal/assets/65522975/1efd6c31-a9c7-4158-8b69-b6285dafa91d)

1 lagi. Itu `Content.tsx` sama `Links.tsx` ga perlu dimasukin lagi ke folder component. disejajarin aja sama `Sidebar.tsx`

2023-07-29 08:23 UTC, msyahrulsp requested changes
Ini tolong sekalian di ubah chi

2023-07-29 08:23 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +              }
Tambahin buat pas hover

2023-07-29 08:23 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +                    }
Tambahin buat pas hover

2023-07-29 08:25 UTC, msyahrulsp commented on src/layout/index.tsx
> +          </Box>
Ini titip juga supaya si childrennya kek di figma, otomatis bg putih, ada border radius terus dikelilingin bg black

2023-07-29 08:27 UTC, msyahrulsp commented
Sama, itu yg pages, ndak perlu folder admin/mentor, langsung aja di pages. Biar nanti kondisionalnya langsung dipage itu. Tolong ya @ashnchiquita

2023-07-29 08:36 UTC, msyahrulsp commented on src/layout/index.tsx
> +          </Box>
terus si children ada padding juga, biar serasi semua paddingnya

2023-07-30 06:36 UTC, msyahrulsp requested changes
minor fix chi :(

2023-07-30 06:36 UTC, msyahrulsp commented on src/component/icon-from-image.tsx
> +  [key: string]: any;
jangan any, ini bikin gagal build

2023-07-30 06:36 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +  component: any;
jangan any, ini bikin gagal build

2023-07-30 06:36 UTC, msyahrulsp commented on src/layout/index.tsx
> +            my={fullBg ? 0 : 6}
```suggestion
            my={fullBg ? 0 : '2vh'}
```

2023-07-30 06:36 UTC, msyahrulsp commented on src/layout/index.tsx
> +            height={fullBg ? '100vh' : '94vh'}
```suggestion
            height={fullBg ? '100vh' : '96vh'}
```

2023-07-30 06:36 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +                  bg: activeRoute(route.path.toLowerCase()) ? white : gray
on hover ini ngikut color sama bgnya sama active router

2023-07-30 06:36 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +      <VStack spacing={2} alignItems={'start'}>
spacing vstacknya coba kecilin. 2 kebesaran keliatannya

2023-07-30 06:41 UTC, ashnchiquita commented on src/component/sidebar/Links.tsx
> +                  bg: activeRoute(route.path.toLowerCase()) ? white : gray
maksudnya berarti kalo hover warnanya putih kak?

2023-07-30 06:48 UTC, msyahrulsp commented on src/component/sidebar/Links.tsx
> +                  bg: activeRoute(route.path.toLowerCase()) ? white : gray
yes, bg putih sama colornya purple

2023-07-31 02:44 UTC, msyahrulsp approved these changes
LGTM

2023-07-31 02:44 UTC, merged