Story/group information management
KATITB2023/dashboard-internal pull request #15
Opened 2023-07-27 04:35 UTC by Julian-Caleb

## Story/Task

- [FE] Group Management 
https://trello.com/c/ZIeFvhIg
- [FE] Group Information Page
https://trello.com/c/WzHPdEGV

## Summary

- Add Group Management Page for mentor
- Add Group Information Page for admin

## Screenshot

- Group Information Page (null)
![Screenshot (1530)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/e5d97833-3edf-4362-81f1-7bd84677fde3)

- Group Information Page for Desktop
![Screenshot (1532)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/5ed29181-4bcd-4c4c-8c42-2e881363dff7)

- Group Management Page for Desktop
![Screenshot (1533)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/e59a8e7d-1998-4865-be3d-3caff8547782)

2023-07-27 08:25 UTC, msyahrulsp commented
Branchnya tolong dipindah ke `staging` dlu @Julian-Caleb

2023-07-27 08:54 UTC, Julian-Caleb commented
> Branchnya tolong dipindah ke `staging` dlu @Julian-Caleb

Maksudnya bagaimana Kak?

2023-07-27 09:09 UTC, msyahrulsp commented
> Maksudnya bagaimana Kak?

Yang sekarang target branch buat mergenya itu `master`, harusnya ke `staging` wkwkwkwk

2023-07-27 09:22 UTC, Julian-Caleb commented
Oh oke Kak

2023-07-30 04:30 UTC, msyahrulsp requested changes
- Buat semua placeholder bisa dihapus aja, biar nanti tinggal pasang layout yang udah ada
- Perhatiin juga ukurant font dipagenya, sesuain stylenya juga sama yang ada di figma
- Yang tooltip detail tugas aku cek belum ada juga, jadi jangan lupa bagian itu

2023-08-01 16:03 UTC, Julian-Caleb commented
## Story/Task

- [FE] Group Management 
https://trello.com/c/ZIeFvhIg
- [FE] Group Information Page
https://trello.com/c/WzHPdEGV

## Summary

- Fix / refactor Group Management Page for mentor
- Fix / refactor Information Page for admin
- Add description for task and attendance

## Screenshot

- Group Information Page (null)
![Screenshot (1562)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/d9767e33-cda1-42c5-b9aa-4730f9db5a43)
![Screenshot (1564)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/f03f2a5e-4495-4c3f-89f0-8d110c401884)

- Group Information Page for Desktop
![Screenshot (1565)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/702ea5f7-e1a5-45d5-b042-1c22f9b90236)
![Screenshot (1568)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/3c97770a-6966-48e0-b540-d3bb26035590)

- Group Management Page for Desktop
![Screenshot (1569)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/fb86d3dd-4436-4763-a150-6536f50653ab)
![Screenshot (1571)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/e7f9d1f0-f598-4bce-a5d5-a0da077c07c8)

2023-08-01 17:02 UTC, Julian-Caleb commented
## Story/Task

- [FE] Group Management 
https://trello.com/c/ZIeFvhIg
- [FE] Group Information Page
https://trello.com/c/WzHPdEGV

## Summary

- Fix / refactor and add Group Management Page for mentor to pages
- Fix / refactor and add Group Information Page for admin to pages
- Add description for task and attendance

## Screenshot

- Group Information Page (null)
![Screenshot (1573)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/40b4a016-ebf1-494c-b6fb-5e1c52ddbfd7)

- Group Information Page for Desktop
![Screenshot (1575)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/d1f334c6-1634-4a75-a5dd-a1a337bf289f)
![Screenshot (1576)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/c3da7e95-9ddb-47db-9cbd-e3bff0f60dae)

- Group Management Page for Desktop
![Screenshot (1577)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/ea3052c7-99f4-4f12-bd3a-f4b1e12545aa)
![Screenshot (1578)](https://github.com/KATITB2023/dashboard-internal/assets/90737534/7bfc4fe1-696e-4ada-8a4e-f0bbcf264f5a)

2023-08-05 05:06 UTC, msyahrulsp requested changes
Ini tolong diubah ya. Konekin juga sekalian sama be sama hapus sekalian gambar2 placeholdernyaa 🫡🫡

2023-08-05 05:06 UTC, msyahrulsp commented on src/pages/group-management.tsx
> +          </Box>
Pake komponen header dari staging

2023-08-05 05:06 UTC, msyahrulsp commented on src/pages/group-management.tsx
> +          >
widthnya ga perlu di set manual. terus kasih bikin supaya centered vertically sama komponen header nanti

2023-08-05 05:06 UTC, msyahrulsp commented on src/pages/group-management.tsx
> +              />
Pake [Avatar](https://chakra-ui.com/docs/components/avatar/usage)

2023-08-06 21:49 UTC, Julian-Caleb commented on src/pages/group-information.tsx
> +          </Box>
```suggestion
          <Header title='Group Information' />
```

2023-08-06 21:51 UTC, Julian-Caleb commented
Saya usahakan ya Kak, mohon bantuannya :)

2023-08-06 21:53 UTC, Julian-Caleb commented on src/pages/group-management.tsx
> +          </Box>
```suggestion
          <Header title='Group Management' />
```

2023-08-06 21:54 UTC, Julian-Caleb commented on src/component/group-information-management/MentorBox.tsx
> +      maxH='96px'
```suggestion
      <Flex
        width='480px'
        minW='200px'
        bg='#0B0A0A'
        p={4}
        borderRadius='25px'
        boxShadow='0 3px 15px -3px #FFFC83'
        color='white'
       alignItems='center'
    >
```

2023-08-06 22:14 UTC, Julian-Caleb commented on src/pages/group-information.tsx
> +                  <Image src='/images/dropdown_icon.png' alt='dropdown_icon' />
```suggestion
                  <RiArrowDownSLine size={24} />
```

2023-08-06 22:22 UTC, Julian-Caleb commented on src/component/group-information-management/MembersTable.tsx
> +            </svg>
```suggestion
            <BsCheckCircle size={24} color="#4909B3" /> 
            ) : (
            <BsCheckCircle size={24} color="#9B9B9B" /> 
```

2023-08-06 22:30 UTC, Julian-Caleb commented on src/component/group-information-management/MembersTable.tsx
> +                  />
```suggestion
                  <FaEye
                    size={24}
                    color="#4b19a7"
                    cursor="pointer"
                    onClick={() => toggleTooltip({ rowIndex, columnIndex: 6 }, TooltipType.Attendance)}
                  />
```

2023-08-06 22:31 UTC, Julian-Caleb commented on src/component/group-information-management/MembersTable.tsx
> +                  />
```suggestion
                  <FaEye
                    size={24}
                    color="#4b19a7"
                    cursor="pointer"
                    onClick={() => toggleTooltip({ rowIndex, columnIndex: 5 }, TooltipType.Task)}
                  />
```

2023-08-06 22:32 UTC, Julian-Caleb commented on src/component/group-information-management/MembersTable.tsx
> +            </svg>
```suggestion
            <BsCheckCircle size={24} color="#4909B3" /> 
          ) : (
            <BsCheckCircle size={24} color="#9B9B9B" /> 
```

2023-08-07 01:37 UTC, msyahrulsp commented
Sip2, commit aja ya kalau udah pada diresolve. Kalau masih bingung, boleh tanya aja langsung ✌️

2023-08-07 04:09 UTC, Julian-Caleb commented on src/pages/group-information.tsx
> +                ))}
Cara manggilnya ke page bagaimana ya Kak?

2023-08-07 04:13 UTC, msyahrulsp commented on src/pages/group-information.tsx
> +                ))}
Hmm, ku belum cek lagi nama fungsi di benya apa. Paling kalua gimananya, bisa liat yg dari [dikpus](https://github.com/KATITB2023/dikpus-info/tree/main/src/component)

2023-08-07 04:16 UTC, msyahrulsp commented on src/pages/group-information.tsx
> +                ))}
![image](https://github.com/KATITB2023/dashboard-internal/assets/65522975/994a47b6-a34d-4809-a844-1264e072a30a)

kurleb gitu

2023-08-07 16:05 UTC, Julian-Caleb commented
Maaf Kak, yang berhubungan dengan database sepertinya tidak bisa selesai malam ini karena saya masih bingung

2023-08-11 10:11 UTC, merged