feat(draft): add new login page
KATITB2023/dashboard-internal pull request #23
Opened 2023-07-30 15:44 UTC by soezyxst

## Story/Task

_Link ke story/task di Trello_

## Summary

- _add new version of login page_

## Screenshot

_Sediakan screenshot_: \

2023-07-31 02:56 UTC, msyahrulsp requested changes
Dah keren banget

Ada minor fix tapi 🥲. Folder .vscodenya hapus, sama login dipindah di dalem folder `pages` aja langsung as `index.tsx`. Karena kalau di dashboard itu awal2 harus login, ga kayak oskm

2023-07-31 03:01 UTC, soezyxst commented
syap kak

2023-07-31 06:07 UTC, msyahrulsp commented
Conflictnya resolve dlu @soezyxst

2023-07-31 06:17 UTC, soezyxst commented
aman kak

2023-07-31 06:27 UTC, msyahrulsp commented
> aman kak

wkwkwkw, cuman 1 line diliat

2023-07-31 06:32 UTC, msyahrulsp commented
![image](https://github.com/KATITB2023/dashboard-internal/assets/65522975/08d7a9e3-ab13-4c6e-b5eb-2c55591b9cce)
 
buat login dashboard jangan pake layout

2023-07-31 06:35 UTC, soezyxst commented
oh layoutnya hapus aja ya

2023-07-31 06:37 UTC, msyahrulsp commented
> layout

iya, buat ngubah title tabnya, manual tambah <Head>-nya

2023-07-31 06:49 UTC, msyahrulsp commented
@soezyxst, ini baru masuk. bisa tolong desain desktop samain kek yang dimobile? Jadi si div login gaperlu background kotak ataupun planetnya. Buat figma harusnya dah ke update

> Maafkan

2023-07-31 06:53 UTC, soezyxst commented
oh siap

2023-07-31 06:59 UTC, soezyxst commented
aman kak

2023-07-31 07:02 UTC, soezyxst commented
login page lumayan ricuh juga yak

2023-07-31 07:38 UTC, msyahrulsp commented
coba yg meteor(?) kalau desktop, mentokin secara verticak. kalau mobile, mentokin horizontal

2023-07-31 07:45 UTC, soezyxst commented
oh boleh kak

2023-07-31 07:53 UTC, msyahrulsp commented
> login page lumayan ricuh juga yak

harap dimaklumi

2023-07-31 08:17 UTC, msyahrulsp commented on src/components/form/ForgetPasswordForm.tsx
> +        <Text>Tenang saja, Voyagers!</Text>
```suggestion
        <Text>Tenang saja, Spacefarers!</Text>
```

2023-08-01 07:47 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +                size={{ base: 'sm', md: 'md' }}
samain sizenya kek yang di atas

2023-08-01 13:36 UTC, soezyxst commented
sudah kak, maaf telat

2023-08-02 04:54 UTC, msyahrulsp approved these changes
LGTM! Boleh sekalian pasang di oskm-info yes, tinggal pasang <Layout> aja dan pasangnya di page `login.tsx` @soezyxst 

> mmf banget btw login harus bikin 2x 🥲🥲🥲🥲

2023-08-02 04:55 UTC, merged

2023-08-03 10:21 UTC, soezyxst commented
maaf kak baru baca, otw tar pasang