Feat/feeds
KATITB2023/dashboard-internal pull request #35
Opened 2023-08-06 17:07 UTC by zen87-byte

## Story/Task
https://trello.com/c/DPwo3u3k

## Summary
- Create attach feature
- Create edit handler raw

## Screenshot
1. Null
<img width="1680" alt="Screenshot 2023-08-06 at 23 44 42" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/99449ec0-a079-418b-b631-858e766e961f">

2. Add New Post
<img width="1680" alt="Screenshot 2023-08-06 at 23 44 57" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/a14d6cdb-5168-42f0-a50a-53bf41d07a50">
<img width="1680" alt="Screenshot 2023-08-06 at 23 45 10" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/dfaf889e-42af-4751-ac50-1edef186b216">
<img width="1680" alt="Screenshot 2023-08-06 at 23 45 19" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/7514659d-9a52-44ea-be2f-4d7d57d42eed">
<img width="1680" alt="Screenshot 2023-08-06 at 23 45 29" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/05034e6a-282a-44f8-8224-3eee3d970701">

3. Uploaded Feeds List
<img width="1677" alt="Screenshot 2023-08-06 at 23 49 57" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/3c90cc95-59ac-4a77-9324-5ac907169b2f">

4. Edit Feed
<img width="1680" alt="Screenshot 2023-08-06 at 23 50 17" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/cd76d016-6981-410f-b37b-20e94b025328">
<img width="1680" alt="Screenshot 2023-08-06 at 23 52 41" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/1e6ee5e1-fa20-4577-9c05-20acc1198e4b">

5. Delete Feed
<img width="1680" alt="Screenshot 2023-08-06 at 23 50 30" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/867427f2-1910-4b96-8d05-9bd6d5cff6e0">
<img width="1680" alt="Screenshot 2023-08-06 at 23 50 05" src="https://github.com/KATITB2023/dashboard-internal/assets/109773467/e6706307-c585-403e-8efe-e6825b75e70a">

2023-08-07 02:25 UTC, msyahrulsp requested changes
- Si button attach image atau attach url ilangin aja. Soalnya input url itu required. Simpennya di atas input text article aja. labelnya `Attachment URL`
- `feeds.svg` hapus aja. Ambil komponen `Header` dari staging
- Hapus folder `img`, si isinya pindah `images`
- Buat icon, pake `react-icons` aja

2023-08-09 08:20 UTC, YakobusIP requested changes

2023-08-09 08:20 UTC, YakobusIP commented on src/pages/feeds.tsx
> +    console.log('Edited feed: ', editedArticle);
tolong dihapus ya

2023-08-09 08:20 UTC, YakobusIP commented on src/pages/feeds.tsx
> +                                                {...register('article', {
bahasanya jangan article deh kayanya, ubah ke content aja

2023-08-09 10:41 UTC, zen87-byte commented on src/pages/feeds.tsx
> +    console.log('Edited feed: ', editedArticle);
untuk rhfnya nanti aku tambahin lagi, saat ini aku hapus dulu local statenya kak

2023-08-12 03:53 UTC, merged