feat/adminDeleteFeed
KATITB2023/dashboard-internal pull request #40
Opened 2023-08-09 12:31 UTC by PanjiSri

## Story/Task

https://trello.com/c/jbCOsCJB

## Summary

Menambahkan fungsi adminDeleteFeed

## Screenshot

![WhatsApp Image 2023-08-09 at 18 35 58](https://github.com/KATITB2023/dashboard-internal/assets/116989429/2c6c46ab-5c97-42d9-a610-6e4c3e91f231)
![WhatsApp Image 2023-08-09 at 18 36 29](https://github.com/KATITB2023/dashboard-internal/assets/116989429/d8ac7b73-59fa-4d01-99a4-c85d66a5830c)
![WhatsApp Image 2023-08-09 at 18 40 03](https://github.com/KATITB2023/dashboard-internal/assets/116989429/db2a11fa-118e-4a26-8e31-3375d8cffc14)

![WhatsApp Image 2023-08-09 at 18 51 50](https://github.com/KATITB2023/dashboard-internal/assets/116989429/697cb0f6-8cfc-4d98-a7cb-eff98a99ccc4)

2023-08-09 13:52 UTC, jasonk19 requested changes

2023-08-09 13:52 UTC, jasonk19 commented on src/server/api/routers/feeds.ts
> +        return feed;
ini return message aja ya
```suggestion
        return {
          message: ""
        };
```

2023-08-09 13:52 UTC, jasonk19 commented on src/server/api/routers/feeds.ts
> +        });
ini bisa langsung delete aja, ga perlu find dulu biar meringankan server

2023-08-09 13:52 UTC, jasonk19 commented on src/server/api/routers/feeds.ts
> +      }
- console nya bisa diapus
- error codenya internal server error, terus isi messagenya di buat lebih deskriptif, yg string di dalem console.error bisa dijadiin messagenya

2023-08-09 14:20 UTC, PanjiSri commented on src/server/api/routers/feeds.ts
> +        return feed;
okee siap kak

2023-08-10 07:43 UTC, YakobusIP approved these changes
makasi yaa

2023-08-10 07:48 UTC, merged