Feat/mentor set assignment
KATITB2023/dashboard-internal pull request #7
Opened 2023-07-22 05:30 UTC by abrahammegantoro

## Story/Task

[_Link ke story/task di Trello_](https://trello.com/c/P1EthLl1)

## Summary

Add setAssignmentScore

## Screenshot

![image](https://github.com/KATITB2023/dashboard-internal/assets/104062877/d0a3f8ff-bff3-4bd6-bd3d-d572c3629c05)

2023-07-23 11:33 UTC, msyahrulsp commented on src/server/api/routers/assignment.ts
> +      }
Ganti jadi `TRPCError`

2023-07-24 00:33 UTC, msyahrulsp requested changes
Tolong diubah ya

2023-07-24 00:33 UTC, msyahrulsp commented on src/server/api/routers/assignment.ts
> +      }
Ganti jadi `TRPCError`

2023-07-24 00:33 UTC, msyahrulsp commented on src/server/api/routers/assignment.ts
> +        },
Ini filterby nya ga dipake kah?

2023-07-24 17:56 UTC, abrahammegantoro commented on src/server/api/routers/assignment.ts
> +        },
Sorry kak, yang procedure getAssignnment bukan bagianku

2023-07-25 12:56 UTC, msyahrulsp commented
Ini branchnya ubah dlu ke staging

2023-07-27 04:58 UTC, closed without merging